spring:
  datasource:
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
app:
  security:
    webhook-secret: ${KEYCLOAK_WEBHOOK_SECRET:dss-webhook-secret-xyz123}

jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_RESOURCE_ID}
      principal-attribute: ${KEYCLOAK_PRINCIPAL_ATTRIBUTE}

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace
debug: true