spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}
  banner:
    location: static/custom-banner.txt

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/${API_VERSION:v1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_RESOURCE_ID:uatf-auth-service}
      principal-attribute: ${KEYCLOAK_PRINCIPAL_ATTRIBUTE:preferred_username}

app:
  security:
    webhook-secret: ${KEYCLOAK_WEBHOOK_SECRET:dss-webhook-secret-xyz123}