version: "3.9"

services:
  # ==========================================
  # INFRAESTRUCTURA (Bases de Datos y Servicios de Terceros)
  # ==========================================
  auth-service-db:
    image: postgres:15-alpine
    container_name: auth-service-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
    restart: always
    volumes:
      - ./infra/auth-service-db:/var/lib/postgresql/data
    networks:
      - dss-net

  postgres-dw:
    build: ./data-layer/postgres-dw
    environment:
      - POSTGRES_USER=${POSTGRES_DW_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DW_PASSWORD}
    networks:
      - dss-net

  neo4j:
    build: ./data-layer/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - dss-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.1
    container_name: uatf-keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KEYCLOAK_WEBHOOK_URL: ${KEYCLOAK_WEBHOOK_URL}
      KEYCLOAK_WEBHOOK_SECRET: ${KEYCLOAK_WEBHOOK_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - ./infra/keycloak/realm:/opt/keycloak/data/import
      - ./infra/keycloak/providers:/opt/keycloak/providers
    networks:
      - dss-net
  rabbitmq:
    image: rabbitmq:4.3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Web UI
    volumes:
      - ./infra/rabbitmq/data:/var/lib/rabbitmq
    networks:
      - dss-net
  apache-hop:
    image: apache/hop:latest
    container_name: apache-hop
    ports:
      - 8080:8080
      - 8181:8181
      - 8180:8180
    environment:
      # Project
      HOP_PROJECT_NAME: university-data-platform
      HOP_PROJECT_FOLDER: /files/project
      # Environment
      HOP_ENVIRONMENT_NAME: production
      HOP_ENVIRONMENT_CONFIG_FILE_NAME_PATHS: /files/config/production.json
      # Execution
      HOP_FILE_PATH: ${PROJECT_HOME}/workflows/main.hwf
      HOP_RUN_CONFIG: local
      HOP_RUN_PARAMETERS: "PARAM_ENV=production"
      # Logging
      HOP_LOG_LEVEL: Basic
      # JVM
      HOP_OPTIONS: "-Xms512m -Xmx2g"
      # JDBC
      HOP_SHARED_JDBC_FOLDERS: /files/jdbc

    volumes:
      - ./infra/hop:/files
    networks:
      - dss-net
  # ==========================================
  # MICROSERVICIOS PROPIOS
  # ==========================================
  auth-service:
    build: ./auth-service
    depends_on:
      - auth-service-db
    restart: on-failure
    environment:
      - SPRING_PROFILE_ACTIVE=${AUTH_SPRING_PROFILE_ACTIVE}
      - SERVER_PORT=${AUTH_SERVER_PORT}
      - DB_URI=${AUTH_DB_URI}
      - DB_USERNAME=${AUTH_DB_USER}
      - DB_PASSWORD=${AUTH_DB_PASSWORD}
      - KEYCLOAK_ISSUER_URI=${AUTH_KEYCLOAK_ISSUER_URI}
      - KEYCLOAK_JWK_SET_URI=${AUTH_KEYCLOAK_JWK_SET_URI}
      - KEYCLOAK_WEBHOOK_SECRET=${KEYCLOAK_WEBHOOK_SECRET}
      - KEYCLOAK_RESOURCE_ID=${AUTH_KEYCLOAK_RESOURCE_ID}
      - KEYCLOAK_PRINCIPAL_ATTRIBUTE=${AUTH_KEYCLOAK_PRINCIPAL_ATTRIBUTE}
    ports:
      - "8000:${AUTH_SERVER_PORT}"
    networks:
      - dss-net

  olap-service:
    build: ./olap-service
    networks:
      - dss-net

  prediction-service:
    build: ./prediction-service
    networks:
      - dss-net

  etl-service:
    build: ./etl-service
    networks:
      - dss-net

  # ==========================================
  # GATEWAY, BFF Y FRONTEND
  # ==========================================
  graphql-bff:
    build: ./gateway/graphql-bff
    depends_on:
      - auth-service
      - olap-service
      - prediction-service
      - etl-service
    networks:
      - dss-net

  gateway:
    build: ./gateway/traefik
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dss-net

  frontend:
    build: ./frontend/nextjs-spa
    ports:
      - "3000:3000"
    networks:
      - dss-net

networks:
  dss-net:
    driver: bridge
